// --- AUTHENTICATION & USERS ---
const ADMIN_TABLE = "admin";
const WISATAWAN_TABLE = "wisatawan";


// --- MASTER DATA SPK (CORE) ---
const WISATA_TABLE = "alternatif_wisata";
const WISATA_GAMBAR_TABLE = "wisata_gambar";
const KRITERIA_TABLE = "kriteria";
const SUB_KRITERIA_TABLE = "sub_kriteria";

// --- TRANSACTION / HISTORY ---
const RIWAYAT_PENCARIAN_TABLE = "riwayat_pencarian";
const HASIL_REKOMENDASI_TABLE = "hasil_rekomendasi";

module.exports = {
  ADMIN_TABLE,
  WISATAWAN_TABLE,
  WISATA_TABLE,
  WISATA_GAMBAR_TABLE,
  KRITERIA_TABLE,
  SUB_KRITERIA_TABLE,
  RIWAYAT_PENCARIAN_TABLE,
  HASIL_REKOMENDASI_TABLE,

  TABLES: {
    ADMIN: ADMIN_TABLE,
    WISATAWAN: WISATAWAN_TABLE,
    WISATA: WISATA_TABLE,
    WISATA_GAMBAR: WISATA_GAMBAR_TABLE,
    KRITERIA: KRITERIA_TABLE,
    SUB_KRITERIA: SUB_KRITERIA_TABLE,
    RIWAYAT_PENCARIAN: RIWAYAT_PENCARIAN_TABLE,
    HASIL_REKOMENDASI: HASIL_REKOMENDASI_TABLE,
  },
};